
import numpy as np
import pandas as pd
import os

loc = os.getcwd()
print(loc)
#note:download data set and place in current working directory
movies = pd.read_csv("Movie-Ratings.csv")

print("Lenght of data is: ", len(movies))
print("First few rows of data: ", movies.head())
#rename column headers to remove spaces so we can use . operator
movies.columns = ['Film', 'Genre', 'CriticRating', 'AudienceRating', 'BudgetMillions', 'Year']
print("First few rows of data: ", movies.head())

#print(movies.info())
# year is more of a category, we won't use it for calculations
#so we don't need it as a number

#how to convert variables into categorical variables
#call the variable in either way:
movies['Film'] #do this if there are spaces in column name
movies.Film

#now convert
movies.Year = movies.Year.astype('category')
movies.Film = movies.Film.astype('category')
movies.Genre = movies.Genre.astype('category')
print(movies.info()) #output shows that film is now a category

print(movies.Genre.cat.categories) #shows which values category holds

print(movies.describe()) #now year is not included in statistics
#generated by describe() bc it's a category, not a number value
